export const VEDIO_DETAIL = 'VEDIO_DETAIL'

export const VEDIO_COMMENT_LIST = 'VEDIO_COMMENT_LIST'

export const VEDIO_COMMENT_COMMIT = 'VEDIO_COMMENT_COMMIT'

export const VEDIO_GIVE_LIKE = 'VEDIO_GIVE_LIKE'

export const VEDIO_COLLECT = 'VEDIO_COLLECT'

export const VEDIO_SHARE = 'VEDIO_SHARE'